# Generated by Django 4.1 on 2022-10-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_duration', models.FloatField(default=0.5)),
                ('event_location', models.CharField(max_length=300)),
                ('event_description', models.CharField(max_length=2000)),
                ('event_start', models.DateTimeField(verbose_name='date start')),
            ],
        ),
    ]
