# Generated by Django 4.1 on 2022-10-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='type',
        ),
    ]
