# Generated by Django 4.1 on 2022-10-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='note',
            name='name',
        ),
    ]
