# Generated by Django 4.1 on 2023-06-19 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_alter_task_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('DE', 'Deadline'), ('FI', 'Fitness'), ('WO', 'Work'), ('FN', 'Fun'), ('ET', 'etc.')], default='DEADLINE', max_length=50),
        ),
    ]
