# Generated by Django 4.1 on 2023-06-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_task_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('DE', 'Deadline'), ('FI', 'Fitness'), ('WO', 'Work'), ('FN', 'Fun'), ('ET', 'etc.')], default='DEADLINE', max_length=50),
        ),
    ]
