# Generated by Django 4.1 on 2023-06-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_type'),
        ('events', '0009_note_user_task_user'),
    ]

    operations = [
    ]
