# Generated by Django 4.1 on 2023-06-21 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_merge_0008_alter_event_type_0009_note_user_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
