# Generated by Django 4.1 on 2022-10-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('DE', 'Deadline'), ('FI', 'Fitness'), ('WO', 'Work'), ('FN', 'Fun')], default='DEADLINE', max_length=50),
        ),
    ]
